[package]
name = "cortex-kit-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
gimli.workspace = true
object.workspace = true
serde.workspace = true
svd-parser.workspace = true
thiserror.workspace = true
